### PR TITLE
Django initial files

### PR DESCRIPTION
**Pull request by nokekip**

### CODE REVIEW

**Review by timontuitoek — APPROVED** [review]
Good review

**Comment by nokekip** [comment]
These are the initial Django files for project

**Review by dev-EstherKubania — COMMENTED** [review]
Created first initial files. Well created.

**Review by timontuitoek — APPROVED** [review]
Good work on boiler plate

**Review by dev-EstherKubania — APPROVED** [review]
good work.

**Comment by timontuitoek** [comment]
Awesome

**Pull request merged**
